/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package battleship;

/**
 *
 * @author pamelamurillo
 */
public class GridPanelView extends javax.swing.JPanel {

    private GridPanel grid;
    /**
     * Creates new form battleBoard
     */
    public GridPanelView(GridPanel grid) {
        this.grid = grid;
        initComponents();
    }
    
    public GridPanel getPanel() {
        return grid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGridText = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblGridText.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        lblGridText.setForeground(new java.awt.Color(0, 204, 204));
        lblGridText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGridText.setText(getPanel().getText() + "");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGridText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblGridText)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblGridText.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGridText;
    // End of variables declaration//GEN-END:variables
}
